[general]
default_scene_sid = ""
reticulum_server = "dev.reticulum.io"
cors_proxy_server = "cors-proxy-dev.reticulum.io"
thumbnail_server = "nearspark-dev.reticulum.io"
non_cors_proxy_domains = "hubs.local,dev.reticulum.io"
postgrest_server = "hubs.local:3000"
ita_server = ""
base_assets_path = "/"
sentry_dsn = ""
ga_tracking_id = ""

[deploy]
type = "none"
