name: hc-pkg
on:
  workflow_dispatch:
   
    
jobs:
  hcpkgrelease:
    uses: Hubs-Foundation/hubs-ops/.github/workflows/HcPkgPreReleaseGitops.yaml@master
    with:
      main: master
      releaseTrackingBranch: hubs-cloud
      qaTestBranch: qa-test
